sudo: required

services:
  - docker

before_install: 
  - docker build -t karthiksgd/go-sky-app-test -f ./application/Dockerfile.dev ./application
  - docker build -t karthiksgd/go-sky-rest-test -f ./rest/Dockerfile.dev ./rest


script: 
  - go test -v ./application/
  - go test -v ./rest/