sudo: required
language: go

services:
  - docker

before_install: 
  - docker build -t app-test -f ./application/Dockerfile.dev ./application
  - docker build -t rest-test -f ./rest/Dockerfile.dev ./rest


script: 
  - go test -v ./application/
  - go test -v ./rest/