sudo: required
language: minimal
# go:
#   - 1.7.x

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - docker build -t karthiksgd/app-test -f ./application/Dockerfile.dev ./application
  - docker build -t karthiksgd/rest-test -f ./rest/Dockerfile.dev ./rest

script:
  - docker run karthiksgd/app-test -- --coverage
  - docker run karthiksgd/rest-test -- --coverage
 