sudo: required
language: go

services:
  - docker

before_install:
  - sudo apt-get install build-essential
  - docker build -t karthiksgd/app-test -f ./application/Dockerfile.dev ./application
  - docker build -t karthiksgd/rest-test -f ./rest/Dockerfile.dev ./rest


script: 
  - go test -v ./application/...
  - go test -v ./rest/...