
FROM golang:1.16-alpine

WORKDIR /usr/app

COPY go.mod ./
COPY go.sum ./

# RUN go mod download
RUN go get -d -v ./...

RUN go install -v ./... && \
    CGO_ENABLED=0 GOOS=linux go test -c

COPY ./ ./

RUN go build -o /sky-api

EXPOSE 8080

# CMD [ "/sky-api" ]
CMD go test ./...

